const ex = require("../src/exercises.js");

describe("33 exercicios basicos", () => {
  test("basico 08 - b08ContarVogais: conta vogais sem diferenciar maiusculas", () => expect(ex.b08ContarVogais("JavaScript")).toBe(3));
  test("basico 09 - b09InverterTexto: inverte uma string", () => expect(ex.b09InverterTexto("teste")).toBe("etset"));
  test("basico 10 - b10MaiorNumero: maior numero do array", () => expect(ex.b10MaiorNumero([3, 9, 1, 6])).toBe(9));
  test("basico 11 - b11MenorNumero: menor numero do array", () => expect(ex.b11MenorNumero([3, -2, 10, 0])).toBe(-2));
  test("basico 12 - b12DobrarNumeros: usa map para dobrar", () => expect(ex.b12DobrarNumeros([1, 2, 3])).toEqual([2, 4, 6]));
  test("basico 13 - b13FiltrarPares: usa filter para pares", () => expect(ex.b13FiltrarPares([1, 2, 3, 4])).toEqual([2, 4]));
  test("basico 14 - b14SomarArray: usa reduce para somar", () => expect(ex.b14SomarArray([1, 2, 3, 4])).toBe(10));
  test("basico 15 - b15EncontrarNome: usa find para localizar nome", () => expect(ex.b15EncontrarNome(["Ana", "Rafa", "Bia"], "Rafa")).toBe("Rafa"));
  test("basico 16 - b16TemNegativo: usa some para negativo", () => expect(ex.b16TemNegativo([1, 2, -3])).toBe(true));
  test("basico 17 - b17TodosPositivos: usa every para positivos", () => expect(ex.b17TodosPositivos([1, 2, 3])).toBe(true));
  test("basico 18 - b18PrimeiroMaiorQue: primeiro numero maior que limite", () => expect(ex.b18PrimeiroMaiorQue([4, 7, 10], 6)).toBe(7));
  test("basico 19 - b19ContarPalavras: conta palavras ignorando espacos extras", () => expect(ex.b19ContarPalavras("  ola mundo JS  ")).toBe(3));
  test("basico 20 - b20Capitalizar: primeira letra maiuscula", () => expect(ex.b20Capitalizar("rafael")).toBe("Rafael"));
  test("basico 21 - b21RemoverDuplicados: remove duplicados com Set", () => expect(ex.b21RemoverDuplicados([1, 2, 2, 3, 1])).toEqual([1, 2, 3]));
  test("basico 22 - b22CriarMapaDePrecos: cria Map produto -> preco", () => expect(ex.b22CriarMapaDePrecos([{ nome: "arroz", preco: 8 }]).get("arroz")).toBe(8));
  test("basico 23 - b23PegarValorObjeto: pega valor pela chave", () => expect(ex.b23PegarValorObjeto({ nome: "Rafa" }, "nome")).toBe("Rafa"));
  test("basico 24 - b24SomarValoresObjeto: soma valores numericos de objeto", () => expect(ex.b24SomarValoresObjeto({ a: 2, b: 3, c: "x" })).toBe(5));
  test("basico 27 - b27EhBissexto: valida ano bissexto", () => expect(ex.b27EhBissexto(2024)).toBe(true));
  test("basico 30 - b30Media: calcula media aritmetica", () => expect(ex.b30Media([8, 10, 6])).toBe(8));
  test("basico 32 - b32JuntarNomes: junta nomes com virgula", () => expect(ex.b32JuntarNomes(["Ana", "Bia", "Caio"])).toBe("Ana, Bia, Caio"));
  test("basico 33 - b33ContemPropriedade: verifica chave propria", () => expect(ex.b33ContemPropriedade({ a: 1 }, "a")).toBe(true));
  test("medio 04 - m04OrdenarNumeros: ordena crescente sem mutar original", () => { const nums = [3, 1, 2]; expect(ex.m04OrdenarNumeros(nums)).toEqual([1, 2, 3]); expect(nums).toEqual([3, 1, 2]); });
  test("medio 05 - m05AgruparPorParidade: separa pares e impares", () => expect(ex.m05AgruparPorParidade([1, 2, 3, 4])).toEqual({ pares: [2, 4], impares: [1, 3] }));
  test("medio 06 - m06ContarOcorrencias: conta itens repetidos", () => expect(ex.m06ContarOcorrencias(["a", "b", "a"])).toEqual({ a: 2, b: 1 }));
  test("medio 07 - m07ProdutosComDesconto: aplica percentual e preserva nome", () => expect(ex.m07ProdutosComDesconto([{ nome: "x", preco: 100 }], 10)).toEqual([{ nome: "x", preco: 90 }]));
  test("medio 08 - m08TotalCarrinho: soma preco * quantidade", () => expect(ex.m08TotalCarrinho([{ preco: 10, quantidade: 2 }, { preco: 5, quantidade: 3 }])).toBe(35));
  //test("medio 09 - m09BuscarUsuarioPorEmail: encontra usuario", () => expect(ex.m09BuscarUsuarioPorEmail([{ nome: "alex", email: "a@x.com" }], "a@x.com")).toEqual({ nome: "alex" }));
  test("medio 09 - m09BuscarUsuarioPorEmail: encontra usuario", () => expect(ex.m09BuscarUsuarioPorEmail([{ email: "a@x.com" }], "a@x.com")).toEqual({ email: "a@x.com" }));
  test("medio 10 - m10UsuariosAtivos: filtra ativos", () => expect(ex.m10UsuariosAtivos([{ id: 1, ativo: true }, { id: 2, ativo: false }])).toEqual([{ id: 1, ativo: true }]));
  test("medio 11 - m11TodosMaioresDeIdade: every idade >= 18", () => expect(ex.m11TodosMaioresDeIdade([{ idade: 18 }, { idade: 20 }])).toBe(true));
  test("medio 12 - m12AlgumProdutoCaro: some preco acima do limite", () => expect(ex.m12AlgumProdutoCaro([{ preco: 20 }, { preco: 200 }], 100)).toBe(true));
  test("medio 13 - m13IndexarPorId: cria objeto por id", () => expect(ex.m13IndexarPorId([{ id: "a", nome: "Ana" }])).toEqual({ a: { id: "a", nome: "Ana" } }));
  test("medio 14 - m14MesclarObjetos: merge com segundo sobrescrevendo", () => expect(ex.m14MesclarObjetos({ a: 1, b: 2 }, { b: 3 })).toEqual({ a: 1, b: 3 }));
  test("medio 15 - m15SelecionarCampos: retorna apenas chaves pedidas", () => expect(ex.m15SelecionarCampos({ a: 1, b: 2, c: 3 }, ["a", "c"])).toEqual({ a: 1, c: 3 }));
  test("medio 16 - m16OmitirCampos: remove chaves pedidas", () => expect(ex.m16OmitirCampos({ a: 1, b: 2, c: 3 }, ["b"])).toEqual({ a: 1, c: 3 }));
  test("medio 17 - m17AchatarUmaCamada: flat de uma camada", () => expect(ex.m17AchatarUmaCamada([1, [2, 3], [4]])).toEqual([1, 2, 3, 4]));
  test("medio 18 - m18Intersecao: itens comuns unicos", () => expect(ex.m18Intersecao([1, 2, 2, 3], [2, 3, 4])).toEqual([2, 3]));
  test("medio 19 - m19Diferenca: itens do primeiro que nao estao no segundo", () => expect(ex.m19Diferenca([1, 2, 3], [2])).toEqual([1, 3]));
  test("medio 20 - m20FrequenciaDeLetras: conta letras ignorando espacos e caixa", () => expect(ex.m20FrequenciaDeLetras("A asa")).toEqual({ a: 3, s: 1 }));
  test("medio 21 - m21Palindromo: ignora acentos, caixa e pontuacao", () => expect(ex.m21Palindromo("A grama e amarga")).toBe(true));
  test("medio 26 - m26TransporMatriz: troca linhas por colunas", () => expect(ex.m26TransporMatriz([[1, 2], [3, 4], [5, 6]])).toEqual([[1, 3, 5], [2, 4, 6]]));
  test("medio 27 - m27RotacionarArray: rotaciona para direita n vezes", () => expect(ex.m27RotacionarArray([1, 2, 3, 4], 2)).toEqual([3, 4, 1, 2]));

});
